### GET request with environment variables
GET {{host}}/news
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibG9sa2VrQG1haWwuY29tIiwiaWF0IjoxNjgxNjc0MjEyLCJleHAiOjE2ODE2Nzc4MTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.zO6D6dk4_hi946ERpvDmOWHcvAPVo1ALJQBEUaVe4AE

### Post requset
POST {{host}}/news
Accept: application/json
Content-Type: application/json

{
  "title": "Biba news",
  "text": "here is some long text",
  "type_id": 8
}

### Update requset
PATCH {{host}}/news/7
Accept: application/json
Content-Type: application/json

{
  "name": "default biba"
}

### Delete request
DELETE {{host}}/news/7
Accept: application/json
